service:
  build: "./"
  environment:
    ENV: development
    DEBUG: "*"
    HOST: 0.0.0.0
    PORT: 5555
  volumes:
    - ./benchmarks:/opt/app/benchmarks
    - ./src:/opt/app/src
    - ./examples:/opt/app/examples
    - ./package.json:/opt/app/package.json
  command: ["./node_modules/.bin/coffee", "./examples/rest/service.coffee"]
  ports:
    - 5555
  dns:
    - 172.17.42.1
    - 8.8.4.4
    - 8.8.8.8
example:
  build: "./"
  environment:
    ENV: development
    DEBUG: "*"
    HOST: service
    PORT: 5555
  volumes:
    - ./benchmarks:/opt/app/benchmarks
    - ./src:/opt/app/src
    - ./examples:/opt/app/examples
    - ./package.json:/opt/app/package.json
  links:
    - service
  command: ["./node_modules/.bin/coffee", "./examples/rest/client.coffee"]
