service:
  build: "./"
  environment:
    ENV: development
    DEBUG: "*"
  volumes:
    - ./src:/opt/app/src
    - ./examples:/opt/app/examples
    - ./package.json:/opt/app/package.json
    # - ./piEx:/opt/app/piEx
  command: ["npm", "run-script", "exampleService"]
  ports:
    - 5555
  dns:
    - 172.17.42.1
    - 8.8.4.4
    - 8.8.8.8
client:
  build: "./"
  environment:
    ENV: development
    DEBUG: "*"
  volumes:
    - ./src:/opt/app/src
    - ./examples:/opt/app/examples
    - ./package.json:/opt/app/package.json
  links:
    - service
  command: ["npm", "run-script", "exampleClient"]
