service:
  build: "./"
  environment:
    ENV: development
    DEBUG: zerorest*
    HOST: 0.0.0.0
    PORT: 5555
  volumes:
    - ./bin:/opt/app/bin
    - ./benchmarks:/opt/app/benchmarks
    - ./src:/opt/app/src
    - ./examples:/opt/app/examples
    - ./package.json:/opt/app/package.json
  command: ["sh", "-c", "./bin/example-service"]
  ports:
    - 5555
  dns:
    - 172.17.42.1
    - 8.8.4.4
    - 8.8.8.8
example:
  build: "./"
  environment:
    ENV: development
    DEBUG: zerorest
    HOST: service
    PORT: 5555
  volumes:
    - ./bin:/opt/app/bin
    - ./benchmarks:/opt/app/benchmarks
    - ./src:/opt/app/src
    - ./examples:/opt/app/examples
    - ./package.json:/opt/app/package.json
  links:
    - service
  command: ["sh", "-c", "./bin/example-client"]
